title: "Digitales Storytelling"
description: Digitales Storytelling in der Kunstgeschichte mit IIIF
baseurl: "/digitales-storytelling"
url: "https://leszimmermann.github.io"
remote_theme: pmarsceill/just-the-docs
permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
aux_links:
  "Über":
    - "/digitales-storytelling/about"
  "Feedback":
    - "/digitales-storytelling/feedback"
  "Impressum":
    - "//www.kunst.uni-frankfurt.de/de/impressum/"
  "Datenschutz":
    - "/digitales-storytelling/datenschutz"
footer_content: "Digitales Storytelling in der Kunstgeschichte mit IIIF ist ein Projekt der <a href=\"https://www.kunst.uni-frankfurt.de/de/mitarbeiter/seiten/prof-dr-jochen-sander/selbstdarstellung\">Städel-Kooperationsprofessur</a> an der Goethe-Universität Frankfurt"
color_scheme: nil
ga_tracking: UA-174905502-1
ga_tracking_anonymize_ip: true

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
